apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ibm-entitlement-key
  namespace: cp4i-apic
spec:
  encryptedData:
    .dockerconfigjson: AgCY7zz0hJtU93zpZSaFopxbF6dYHtJKyy8GgNXoepjJ5LlZrIGI/vSz2Tr/Wy5UVMJmszZUtwOeC7muREGzjxKkw13Bu56WV7o8x4ej8zZZKZYZT7iYN4bBY4H1DEolR2jQ40fWpFaSXe0Nr4b9x+vGt1Vgwka4lA2Lca/SKz5p/gpxPoDcIBKoum2nvC8uaJzyiDBgZdrcwknTbD07UCCuPsXKtcDxa3Q7GdgWTBMyaG4/bY+My6Ww/Bmmy9cdmj29jCN5r65wVlwP5Rt3ATjstkrgcxPxY09fYdpa6AJwl3kpKuQSulTMnj6yw6mCeDe+IHzfooV1f5XouzhSnecoSCrjEhwckPnUP1/KjUmGV3YMu70+5VuS/EUI8uQM7ASKAWaLe3/wLdQdEevp89emYhMP0+E2dUAJBFLLQqiYhhq7vNdkZQPiBWI7+OmtHBtocaJ1Rf8BaAdjF0AyBVkaFgU/XsArFKz0Z+IUAAG+lJY71WUXNDjliZGADqjW8IjCzsG15CyOUa5duRb3V/1YRmsImHl7/U7gVamj3KQeNzayxqH5UvkfowN7z1UTgOfBYJPWbLlV8F4RQEXIRvEYi/NBcWLvfZPow5REBP/ZvVfhB/9/DPfVcM2jdt+iKkbX1/BfPlSeZMG1peTJEHckTFIABxdrOtI0LYADwH/4CY/hXBOvUk5IUsR9Zc/Mh4EH8Wa7HZd0eSV8J6eLAAORShA/Da2ABXjm8YBVB3zNgUDUClCWTX5ST3pABA0LjwOBcWuQ4HE8eoBYFWUTixrBB5YcLTAWR0imygHmEAKOLRxMa5dFLLhxeppT/BSs6SweFxdoH5I0BnKwgObt3aw6X5MgWapQSKzfoUcxtxy+ni4XmZiQZJD8waz81enlI1GqoYZOwYxNoJi+hVj9XHCcNHuR8zK4sgYThhtEgQZOtvAjkMNA6k4tcfv2QVvQWaxbb3RlxwkY/8/YvDisdIcBS2MC5h4PztKTbgYmb9etbnxRCac3SFvvmKZGKIr/xA2+l7Ee3eCYvKCkBXGesBGiTnRsL0lq9yio+nrsvKVViAbWGPaVc2N460maDpw09l0tsTb24P/73toZk29BhSkk6z4gXC0AJRWzQOcf76p+J2IqRZFRlx5RAnPO2orqNv7YEbCmOiVYkGh3o6KOxQTQT8DIrsf98PvpkBvpjnEB6l+zfq3bUFijOQDD4HLn6KA6S3dxHbsti/VguSpF1td0ZshHCkId4PmGVnqVDm1LXBQekDvWj90vfJ0GCwdXxcpdwEMR7D2aGFVqW2JaC78aF95FQ8XE4v7AT/Qpi9YIDs7xyU2ASvYRnm+wztyIYaGa
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: ibm-entitlement-key
      namespace: cp4i-apic
    type: kubernetes.io/dockerconfigjson

